// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk8Hs2tUKRxWJJcrFIONvRqkTNzCcgAd8',
    appId: '1:513236189073:web:b125a309dfcca09ec12430',
    messagingSenderId: '513236189073',
    projectId: 'unisara-ai',
    authDomain: 'unisara-ai.firebaseapp.com',
    storageBucket: 'unisara-ai.appspot.com',
    measurementId: 'G-J2G3J4RJRS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi_fW_FtBHxX484iyFGuWZmnz82husLh0',
    appId: '1:513236189073:ios:a6f8d04fce3e6877c12430',
    messagingSenderId: '513236189073',
    projectId: 'unisara-ai',
    storageBucket: 'unisara-ai.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk8Hs2tUKRxWJJcrFIONvRqkTNzCcgAd8',
    appId: '1:513236189073:web:811ef5de82516cc0c12430',
    messagingSenderId: '513236189073',
    projectId: 'unisara-ai',
    authDomain: 'unisara-ai.firebaseapp.com',
    storageBucket: 'unisara-ai.appspot.com',
    measurementId: 'G-YRR95RQH9N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi_fW_FtBHxX484iyFGuWZmnz82husLh0',
    appId: '1:513236189073:ios:a6f8d04fce3e6877c12430',
    messagingSenderId: '513236189073',
    projectId: 'unisara-ai',
    storageBucket: 'unisara-ai.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmrf1Ha3M8Qx4RDZi3DE_oiKupq1qj1fA',
    appId: '1:513236189073:android:53c12b7a9edf459ec12430',
    messagingSenderId: '513236189073',
    projectId: 'unisara-ai',
    storageBucket: 'unisara-ai.appspot.com',
  );

}